title: Andreas K. Brandh√∏j
description: Testing can take many shapes and forms choosing the right one is critical.
show_downloads: true

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

cayman-blog:
  date_format: "%b %-d, %Y"

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
